use_frameworks!
platform :ios, '11.0'

target 'SimpleChat' do 

    pod 'AgoraRtcEngine_iOS'
    pod 'MBProgressHUD'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'HyphenateChat'
    pod 'SDWebImage'
    pod 'FMDB'
    pod 'EaseCallKit'
    pod 'EaseIMKit'
    pod 'DLPhotoPicker' 

end

